# Generated by Django 5.2.12 on 2026-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=200)),
                ('metric', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('scrape_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
