# Generated by Django 5.2.12 on 2026-04-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='scrape_date',
            field=models.DateTimeField(),
        ),
    ]
